# Generated by Django 6.0.6 on 2026-07-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('users', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('workspace', 'title'), name='unique_document_title_per_workspace'),
        ),
    ]
