# Generated by Django 6.0.6 on 2026-07-04 16:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_unique_document_title_per_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='tags', to='documents.document')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
